spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://${DB_HOST:127.0.0.1}:3307/quickpay?allowPublicKeyRetrieval=true&useSSL=false
    username: ${DB_USER:qpayuser}
    password: ${DB_PASSWD:qpaypaswd}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true